/*
Pulp 3 API

Fetch, Upload, Organize, and Distribute Software Packages

API version: v3
Contact: pulp-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zest

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
	"reflect"
)


// VulnReportAPIService VulnReportAPI service
type VulnReportAPIService service

type VulnReportAPIVulnReportDeleteRequest struct {
	ctx context.Context
	ApiService *VulnReportAPIService
	vulnerabilityReportHref string
	xTaskDiagnostics *[]string
}

// List of profilers to use on tasks.
func (r VulnReportAPIVulnReportDeleteRequest) XTaskDiagnostics(xTaskDiagnostics []string) VulnReportAPIVulnReportDeleteRequest {
	r.xTaskDiagnostics = &xTaskDiagnostics
	return r
}

func (r VulnReportAPIVulnReportDeleteRequest) Execute() (*http.Response, error) {
	return r.ApiService.VulnReportDeleteExecute(r)
}

/*
VulnReportDelete Delete a vulnerability report

A customized named ModelViewSet that knows how to register itself with the Pulp API router.This viewset is discoverable by its name."Normal" Django Models and Master/Detail models are supported by the ``register_with`` method.Attributes:    lookup_field (str): The name of the field by which an object should be looked up, in        addition to any parent lookups if this ViewSet is nested. Defaults to 'pk'    endpoint_name (str): The name of the final path segment that should identify the ViewSet's        collection endpoint.    nest_prefix (str): Optional prefix under which this ViewSet should be nested. This must        correspond to the "parent_prefix" of a router with rest_framework_nested.NestedMixin.        None indicates this ViewSet should not be nested.    parent_lookup_kwargs (dict): Optional mapping of key names that would appear in self.kwargs        to django model filter expressions that can be used with the corresponding value from        self.kwargs, used only by a nested ViewSet to filter based on the parent object's        identity.    schema (DefaultSchema): The schema class to use by default in a viewset.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param vulnerabilityReportHref
 @return VulnReportAPIVulnReportDeleteRequest
*/
func (a *VulnReportAPIService) VulnReportDelete(ctx context.Context, vulnerabilityReportHref string) VulnReportAPIVulnReportDeleteRequest {
	return VulnReportAPIVulnReportDeleteRequest{
		ApiService: a,
		ctx: ctx,
		vulnerabilityReportHref: vulnerabilityReportHref,
	}
}

// Execute executes the request
func (a *VulnReportAPIService) VulnReportDeleteExecute(r VulnReportAPIVulnReportDeleteRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "VulnReportAPIService.VulnReportDelete")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/{vulnerability_report_href}"
	localVarPath = strings.Replace(localVarPath, "{"+"vulnerability_report_href"+"}", url.PathEscape(parameterValueToString(r.vulnerabilityReportHref, "vulnerabilityReportHref")), -1)
	localVarPath, _ = url.PathUnescape(localVarPath)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xTaskDiagnostics != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Task-Diagnostics", r.xTaskDiagnostics, "simple", "csv")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type VulnReportAPIVulnReportListRequest struct {
	ctx context.Context
	ApiService *VulnReportAPIService
	pulpDomain string
	xTaskDiagnostics *[]string
	limit *int32
	offset *int32
	ordering *[]string
	prnIn *[]string
	pulpHrefIn *[]string
	pulpIdIn *[]string
	q *string
	repoVersions *string
	fields *[]string
	excludeFields *[]string
}

// List of profilers to use on tasks.
func (r VulnReportAPIVulnReportListRequest) XTaskDiagnostics(xTaskDiagnostics []string) VulnReportAPIVulnReportListRequest {
	r.xTaskDiagnostics = &xTaskDiagnostics
	return r
}

// Number of results to return per page.
func (r VulnReportAPIVulnReportListRequest) Limit(limit int32) VulnReportAPIVulnReportListRequest {
	r.limit = &limit
	return r
}

// The initial index from which to return the results.
func (r VulnReportAPIVulnReportListRequest) Offset(offset int32) VulnReportAPIVulnReportListRequest {
	r.offset = &offset
	return r
}

// Ordering* &#x60;pulp_id&#x60; - Pulp id* &#x60;-pulp_id&#x60; - Pulp id (descending)* &#x60;pulp_created&#x60; - Pulp created* &#x60;-pulp_created&#x60; - Pulp created (descending)* &#x60;pulp_last_updated&#x60; - Pulp last updated* &#x60;-pulp_last_updated&#x60; - Pulp last updated (descending)* &#x60;vulns&#x60; - Vulns* &#x60;-vulns&#x60; - Vulns (descending)* &#x60;pk&#x60; - Pk* &#x60;-pk&#x60; - Pk (descending)
func (r VulnReportAPIVulnReportListRequest) Ordering(ordering []string) VulnReportAPIVulnReportListRequest {
	r.ordering = &ordering
	return r
}

// Multiple values may be separated by commas.
func (r VulnReportAPIVulnReportListRequest) PrnIn(prnIn []string) VulnReportAPIVulnReportListRequest {
	r.prnIn = &prnIn
	return r
}

// Multiple values may be separated by commas.
func (r VulnReportAPIVulnReportListRequest) PulpHrefIn(pulpHrefIn []string) VulnReportAPIVulnReportListRequest {
	r.pulpHrefIn = &pulpHrefIn
	return r
}

// Multiple values may be separated by commas.
func (r VulnReportAPIVulnReportListRequest) PulpIdIn(pulpIdIn []string) VulnReportAPIVulnReportListRequest {
	r.pulpIdIn = &pulpIdIn
	return r
}

// Filter results by using NOT, AND and OR operations on other filters
func (r VulnReportAPIVulnReportListRequest) Q(q string) VulnReportAPIVulnReportListRequest {
	r.q = &q
	return r
}

// Filter results where repo_versions matches value
func (r VulnReportAPIVulnReportListRequest) RepoVersions(repoVersions string) VulnReportAPIVulnReportListRequest {
	r.repoVersions = &repoVersions
	return r
}

// A list of fields to include in the response.
func (r VulnReportAPIVulnReportListRequest) Fields(fields []string) VulnReportAPIVulnReportListRequest {
	r.fields = &fields
	return r
}

// A list of fields to exclude from the response.
func (r VulnReportAPIVulnReportListRequest) ExcludeFields(excludeFields []string) VulnReportAPIVulnReportListRequest {
	r.excludeFields = &excludeFields
	return r
}

func (r VulnReportAPIVulnReportListRequest) Execute() (*PaginatedVulnerabilityReportResponseList, *http.Response, error) {
	return r.ApiService.VulnReportListExecute(r)
}

/*
VulnReportList List vulnerability reports

A customized named ModelViewSet that knows how to register itself with the Pulp API router.This viewset is discoverable by its name."Normal" Django Models and Master/Detail models are supported by the ``register_with`` method.Attributes:    lookup_field (str): The name of the field by which an object should be looked up, in        addition to any parent lookups if this ViewSet is nested. Defaults to 'pk'    endpoint_name (str): The name of the final path segment that should identify the ViewSet's        collection endpoint.    nest_prefix (str): Optional prefix under which this ViewSet should be nested. This must        correspond to the "parent_prefix" of a router with rest_framework_nested.NestedMixin.        None indicates this ViewSet should not be nested.    parent_lookup_kwargs (dict): Optional mapping of key names that would appear in self.kwargs        to django model filter expressions that can be used with the corresponding value from        self.kwargs, used only by a nested ViewSet to filter based on the parent object's        identity.    schema (DefaultSchema): The schema class to use by default in a viewset.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param pulpDomain
 @return VulnReportAPIVulnReportListRequest
*/
func (a *VulnReportAPIService) VulnReportList(ctx context.Context, pulpDomain string) VulnReportAPIVulnReportListRequest {
	return VulnReportAPIVulnReportListRequest{
		ApiService: a,
		ctx: ctx,
		pulpDomain: pulpDomain,
	}
}

// Execute executes the request
//  @return PaginatedVulnerabilityReportResponseList
func (a *VulnReportAPIService) VulnReportListExecute(r VulnReportAPIVulnReportListRequest) (*PaginatedVulnerabilityReportResponseList, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *PaginatedVulnerabilityReportResponseList
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "VulnReportAPIService.VulnReportList")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/pulp/{pulp_domain}/api/v3/vuln_report/"
	localVarPath = strings.Replace(localVarPath, "{"+"pulp_domain"+"}", url.PathEscape(parameterValueToString(r.pulpDomain, "pulpDomain")), -1)
	localVarPath, _ = url.PathUnescape(localVarPath)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	}
	if r.offset != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "offset", r.offset, "form", "")
	}
	if r.ordering != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "ordering", r.ordering, "form", "csv")
	}
	if r.prnIn != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "prn__in", r.prnIn, "form", "csv")
	}
	if r.pulpHrefIn != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "pulp_href__in", r.pulpHrefIn, "form", "csv")
	}
	if r.pulpIdIn != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "pulp_id__in", r.pulpIdIn, "form", "csv")
	}
	if r.q != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "q", r.q, "form", "")
	}
	if r.repoVersions != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "repo_versions", r.repoVersions, "form", "")
	}
	if r.fields != nil {
		t := *r.fields
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
                               parameterAddToHeaderOrQuery(localVarQueryParams, "fields", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "fields", t, "form", "multi")
		}
	}
	if r.excludeFields != nil {
		t := *r.excludeFields
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
                               parameterAddToHeaderOrQuery(localVarQueryParams, "exclude_fields", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "exclude_fields", t, "form", "multi")
		}
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xTaskDiagnostics != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Task-Diagnostics", r.xTaskDiagnostics, "simple", "csv")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type VulnReportAPIVulnReportReadRequest struct {
	ctx context.Context
	ApiService *VulnReportAPIService
	vulnerabilityReportHref string
	xTaskDiagnostics *[]string
	fields *[]string
	excludeFields *[]string
}

// List of profilers to use on tasks.
func (r VulnReportAPIVulnReportReadRequest) XTaskDiagnostics(xTaskDiagnostics []string) VulnReportAPIVulnReportReadRequest {
	r.xTaskDiagnostics = &xTaskDiagnostics
	return r
}

// A list of fields to include in the response.
func (r VulnReportAPIVulnReportReadRequest) Fields(fields []string) VulnReportAPIVulnReportReadRequest {
	r.fields = &fields
	return r
}

// A list of fields to exclude from the response.
func (r VulnReportAPIVulnReportReadRequest) ExcludeFields(excludeFields []string) VulnReportAPIVulnReportReadRequest {
	r.excludeFields = &excludeFields
	return r
}

func (r VulnReportAPIVulnReportReadRequest) Execute() (*VulnerabilityReportResponse, *http.Response, error) {
	return r.ApiService.VulnReportReadExecute(r)
}

/*
VulnReportRead Inspect a vulnerability report

A customized named ModelViewSet that knows how to register itself with the Pulp API router.This viewset is discoverable by its name."Normal" Django Models and Master/Detail models are supported by the ``register_with`` method.Attributes:    lookup_field (str): The name of the field by which an object should be looked up, in        addition to any parent lookups if this ViewSet is nested. Defaults to 'pk'    endpoint_name (str): The name of the final path segment that should identify the ViewSet's        collection endpoint.    nest_prefix (str): Optional prefix under which this ViewSet should be nested. This must        correspond to the "parent_prefix" of a router with rest_framework_nested.NestedMixin.        None indicates this ViewSet should not be nested.    parent_lookup_kwargs (dict): Optional mapping of key names that would appear in self.kwargs        to django model filter expressions that can be used with the corresponding value from        self.kwargs, used only by a nested ViewSet to filter based on the parent object's        identity.    schema (DefaultSchema): The schema class to use by default in a viewset.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param vulnerabilityReportHref
 @return VulnReportAPIVulnReportReadRequest
*/
func (a *VulnReportAPIService) VulnReportRead(ctx context.Context, vulnerabilityReportHref string) VulnReportAPIVulnReportReadRequest {
	return VulnReportAPIVulnReportReadRequest{
		ApiService: a,
		ctx: ctx,
		vulnerabilityReportHref: vulnerabilityReportHref,
	}
}

// Execute executes the request
//  @return VulnerabilityReportResponse
func (a *VulnReportAPIService) VulnReportReadExecute(r VulnReportAPIVulnReportReadRequest) (*VulnerabilityReportResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *VulnerabilityReportResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "VulnReportAPIService.VulnReportRead")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/{vulnerability_report_href}"
	localVarPath = strings.Replace(localVarPath, "{"+"vulnerability_report_href"+"}", url.PathEscape(parameterValueToString(r.vulnerabilityReportHref, "vulnerabilityReportHref")), -1)
	localVarPath, _ = url.PathUnescape(localVarPath)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.fields != nil {
		t := *r.fields
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
                               parameterAddToHeaderOrQuery(localVarQueryParams, "fields", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "fields", t, "form", "multi")
		}
	}
	if r.excludeFields != nil {
		t := *r.excludeFields
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
                               parameterAddToHeaderOrQuery(localVarQueryParams, "exclude_fields", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "exclude_fields", t, "form", "multi")
		}
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xTaskDiagnostics != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Task-Diagnostics", r.xTaskDiagnostics, "simple", "csv")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
