/*
Pulp 3 API

Fetch, Upload, Organize, and Distribute Software Packages

API version: v3
Contact: pulp-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zest

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
	"reflect"
)


// ContentOpenpgpUseridAPIService ContentOpenpgpUseridAPI service
type ContentOpenpgpUseridAPIService service

type ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest struct {
	ctx context.Context
	ApiService *ContentOpenpgpUseridAPIService
	pulpDomain string
	xTaskDiagnostics *[]string
	limit *int32
	offset *int32
	ordering *[]string
	orphanedFor *float32
	prnIn *[]string
	pulpHrefIn *[]string
	pulpIdIn *[]string
	pulpLabelSelect *string
	q *string
	repositoryVersion *string
	repositoryVersionAdded *string
	repositoryVersionRemoved *string
	userId *string
	userIdContains *string
	userIdIcontains *string
	userIdIexact *string
	userIdIn *[]string
	userIdIregex *string
	userIdIstartswith *string
	userIdRegex *string
	userIdStartswith *string
	fields *[]string
	excludeFields *[]string
}

// List of profilers to use on tasks.
func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest) XTaskDiagnostics(xTaskDiagnostics []string) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest {
	r.xTaskDiagnostics = &xTaskDiagnostics
	return r
}

// Number of results to return per page.
func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest) Limit(limit int32) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest {
	r.limit = &limit
	return r
}

// The initial index from which to return the results.
func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest) Offset(offset int32) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest {
	r.offset = &offset
	return r
}

// Ordering* &#x60;pulp_id&#x60; - Pulp id* &#x60;-pulp_id&#x60; - Pulp id (descending)* &#x60;pulp_created&#x60; - Pulp created* &#x60;-pulp_created&#x60; - Pulp created (descending)* &#x60;pulp_last_updated&#x60; - Pulp last updated* &#x60;-pulp_last_updated&#x60; - Pulp last updated (descending)* &#x60;pulp_type&#x60; - Pulp type* &#x60;-pulp_type&#x60; - Pulp type (descending)* &#x60;upstream_id&#x60; - Upstream id* &#x60;-upstream_id&#x60; - Upstream id (descending)* &#x60;pulp_labels&#x60; - Pulp labels* &#x60;-pulp_labels&#x60; - Pulp labels (descending)* &#x60;timestamp_of_interest&#x60; - Timestamp of interest* &#x60;-timestamp_of_interest&#x60; - Timestamp of interest (descending)* &#x60;raw_data&#x60; - Raw data* &#x60;-raw_data&#x60; - Raw data (descending)* &#x60;user_id&#x60; - User id* &#x60;-user_id&#x60; - User id (descending)* &#x60;pk&#x60; - Pk* &#x60;-pk&#x60; - Pk (descending)
func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest) Ordering(ordering []string) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest {
	r.ordering = &ordering
	return r
}

// Minutes Content has been orphaned for. -1 uses ORPHAN_PROTECTION_TIME.
func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest) OrphanedFor(orphanedFor float32) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest {
	r.orphanedFor = &orphanedFor
	return r
}

// Multiple values may be separated by commas.
func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest) PrnIn(prnIn []string) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest {
	r.prnIn = &prnIn
	return r
}

// Multiple values may be separated by commas.
func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest) PulpHrefIn(pulpHrefIn []string) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest {
	r.pulpHrefIn = &pulpHrefIn
	return r
}

// Multiple values may be separated by commas.
func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest) PulpIdIn(pulpIdIn []string) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest {
	r.pulpIdIn = &pulpIdIn
	return r
}

// Filter labels by search string
func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest) PulpLabelSelect(pulpLabelSelect string) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest {
	r.pulpLabelSelect = &pulpLabelSelect
	return r
}

// Filter results by using NOT, AND and OR operations on other filters
func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest) Q(q string) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest {
	r.q = &q
	return r
}

// Repository Version referenced by HREF/PRN
func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest) RepositoryVersion(repositoryVersion string) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest {
	r.repositoryVersion = &repositoryVersion
	return r
}

// Repository Version referenced by HREF/PRN
func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest) RepositoryVersionAdded(repositoryVersionAdded string) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest {
	r.repositoryVersionAdded = &repositoryVersionAdded
	return r
}

// Repository Version referenced by HREF/PRN
func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest) RepositoryVersionRemoved(repositoryVersionRemoved string) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest {
	r.repositoryVersionRemoved = &repositoryVersionRemoved
	return r
}

// Filter results where user_id matches value
func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest) UserId(userId string) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest {
	r.userId = &userId
	return r
}

// Filter results where user_id contains value
func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest) UserIdContains(userIdContains string) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest {
	r.userIdContains = &userIdContains
	return r
}

// Filter results where user_id contains value
func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest) UserIdIcontains(userIdIcontains string) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest {
	r.userIdIcontains = &userIdIcontains
	return r
}

// Filter results where user_id matches value
func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest) UserIdIexact(userIdIexact string) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest {
	r.userIdIexact = &userIdIexact
	return r
}

// Filter results where user_id is in a comma-separated list of values
func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest) UserIdIn(userIdIn []string) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest {
	r.userIdIn = &userIdIn
	return r
}

// Filter results where user_id matches regex value
func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest) UserIdIregex(userIdIregex string) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest {
	r.userIdIregex = &userIdIregex
	return r
}

// Filter results where user_id starts with value
func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest) UserIdIstartswith(userIdIstartswith string) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest {
	r.userIdIstartswith = &userIdIstartswith
	return r
}

// Filter results where user_id matches regex value
func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest) UserIdRegex(userIdRegex string) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest {
	r.userIdRegex = &userIdRegex
	return r
}

// Filter results where user_id starts with value
func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest) UserIdStartswith(userIdStartswith string) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest {
	r.userIdStartswith = &userIdStartswith
	return r
}

// A list of fields to include in the response.
func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest) Fields(fields []string) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest {
	r.fields = &fields
	return r
}

// A list of fields to exclude from the response.
func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest) ExcludeFields(excludeFields []string) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest {
	r.excludeFields = &excludeFields
	return r
}

func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest) Execute() (*PaginatedOpenPGPUserIDResponseList, *http.Response, error) {
	return r.ApiService.ContentCoreOpenpgpUseridListExecute(r)
}

/*
ContentCoreOpenpgpUseridList List open pgp user ids

Content viewset that supports only GET by default.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param pulpDomain
 @return ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest
*/
func (a *ContentOpenpgpUseridAPIService) ContentCoreOpenpgpUseridList(ctx context.Context, pulpDomain string) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest {
	return ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest{
		ApiService: a,
		ctx: ctx,
		pulpDomain: pulpDomain,
	}
}

// Execute executes the request
//  @return PaginatedOpenPGPUserIDResponseList
func (a *ContentOpenpgpUseridAPIService) ContentCoreOpenpgpUseridListExecute(r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridListRequest) (*PaginatedOpenPGPUserIDResponseList, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *PaginatedOpenPGPUserIDResponseList
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ContentOpenpgpUseridAPIService.ContentCoreOpenpgpUseridList")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/pulp/{pulp_domain}/api/v3/content/core/openpgp_userid/"
	localVarPath = strings.Replace(localVarPath, "{"+"pulp_domain"+"}", url.PathEscape(parameterValueToString(r.pulpDomain, "pulpDomain")), -1)
	localVarPath, _ = url.PathUnescape(localVarPath)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	}
	if r.offset != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "offset", r.offset, "form", "")
	}
	if r.ordering != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "ordering", r.ordering, "form", "csv")
	}
	if r.orphanedFor != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "orphaned_for", r.orphanedFor, "form", "")
	}
	if r.prnIn != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "prn__in", r.prnIn, "form", "csv")
	}
	if r.pulpHrefIn != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "pulp_href__in", r.pulpHrefIn, "form", "csv")
	}
	if r.pulpIdIn != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "pulp_id__in", r.pulpIdIn, "form", "csv")
	}
	if r.pulpLabelSelect != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "pulp_label_select", r.pulpLabelSelect, "form", "")
	}
	if r.q != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "q", r.q, "form", "")
	}
	if r.repositoryVersion != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "repository_version", r.repositoryVersion, "form", "")
	}
	if r.repositoryVersionAdded != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "repository_version_added", r.repositoryVersionAdded, "form", "")
	}
	if r.repositoryVersionRemoved != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "repository_version_removed", r.repositoryVersionRemoved, "form", "")
	}
	if r.userId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "user_id", r.userId, "form", "")
	}
	if r.userIdContains != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "user_id__contains", r.userIdContains, "form", "")
	}
	if r.userIdIcontains != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "user_id__icontains", r.userIdIcontains, "form", "")
	}
	if r.userIdIexact != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "user_id__iexact", r.userIdIexact, "form", "")
	}
	if r.userIdIn != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "user_id__in", r.userIdIn, "form", "csv")
	}
	if r.userIdIregex != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "user_id__iregex", r.userIdIregex, "form", "")
	}
	if r.userIdIstartswith != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "user_id__istartswith", r.userIdIstartswith, "form", "")
	}
	if r.userIdRegex != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "user_id__regex", r.userIdRegex, "form", "")
	}
	if r.userIdStartswith != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "user_id__startswith", r.userIdStartswith, "form", "")
	}
	if r.fields != nil {
		t := *r.fields
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
                               parameterAddToHeaderOrQuery(localVarQueryParams, "fields", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "fields", t, "form", "multi")
		}
	}
	if r.excludeFields != nil {
		t := *r.excludeFields
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
                               parameterAddToHeaderOrQuery(localVarQueryParams, "exclude_fields", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "exclude_fields", t, "form", "multi")
		}
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xTaskDiagnostics != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Task-Diagnostics", r.xTaskDiagnostics, "simple", "csv")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ContentOpenpgpUseridAPIContentCoreOpenpgpUseridReadRequest struct {
	ctx context.Context
	ApiService *ContentOpenpgpUseridAPIService
	openPGPUserIDHref string
	xTaskDiagnostics *[]string
	fields *[]string
	excludeFields *[]string
}

// List of profilers to use on tasks.
func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridReadRequest) XTaskDiagnostics(xTaskDiagnostics []string) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridReadRequest {
	r.xTaskDiagnostics = &xTaskDiagnostics
	return r
}

// A list of fields to include in the response.
func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridReadRequest) Fields(fields []string) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridReadRequest {
	r.fields = &fields
	return r
}

// A list of fields to exclude from the response.
func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridReadRequest) ExcludeFields(excludeFields []string) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridReadRequest {
	r.excludeFields = &excludeFields
	return r
}

func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridReadRequest) Execute() (*OpenPGPUserIDResponse, *http.Response, error) {
	return r.ApiService.ContentCoreOpenpgpUseridReadExecute(r)
}

/*
ContentCoreOpenpgpUseridRead Inspect an open pgp user id

Content viewset that supports only GET by default.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param openPGPUserIDHref
 @return ContentOpenpgpUseridAPIContentCoreOpenpgpUseridReadRequest
*/
func (a *ContentOpenpgpUseridAPIService) ContentCoreOpenpgpUseridRead(ctx context.Context, openPGPUserIDHref string) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridReadRequest {
	return ContentOpenpgpUseridAPIContentCoreOpenpgpUseridReadRequest{
		ApiService: a,
		ctx: ctx,
		openPGPUserIDHref: openPGPUserIDHref,
	}
}

// Execute executes the request
//  @return OpenPGPUserIDResponse
func (a *ContentOpenpgpUseridAPIService) ContentCoreOpenpgpUseridReadExecute(r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridReadRequest) (*OpenPGPUserIDResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *OpenPGPUserIDResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ContentOpenpgpUseridAPIService.ContentCoreOpenpgpUseridRead")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/{open_p_g_p_user_i_d_href}"
	localVarPath = strings.Replace(localVarPath, "{"+"open_p_g_p_user_i_d_href"+"}", url.PathEscape(parameterValueToString(r.openPGPUserIDHref, "openPGPUserIDHref")), -1)
	localVarPath, _ = url.PathUnescape(localVarPath)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.fields != nil {
		t := *r.fields
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
                               parameterAddToHeaderOrQuery(localVarQueryParams, "fields", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "fields", t, "form", "multi")
		}
	}
	if r.excludeFields != nil {
		t := *r.excludeFields
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
                               parameterAddToHeaderOrQuery(localVarQueryParams, "exclude_fields", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "exclude_fields", t, "form", "multi")
		}
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xTaskDiagnostics != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Task-Diagnostics", r.xTaskDiagnostics, "simple", "csv")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ContentOpenpgpUseridAPIContentCoreOpenpgpUseridSetLabelRequest struct {
	ctx context.Context
	ApiService *ContentOpenpgpUseridAPIService
	openPGPUserIDHref string
	setLabel *SetLabel
	xTaskDiagnostics *[]string
}

func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridSetLabelRequest) SetLabel(setLabel SetLabel) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridSetLabelRequest {
	r.setLabel = &setLabel
	return r
}

// List of profilers to use on tasks.
func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridSetLabelRequest) XTaskDiagnostics(xTaskDiagnostics []string) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridSetLabelRequest {
	r.xTaskDiagnostics = &xTaskDiagnostics
	return r
}

func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridSetLabelRequest) Execute() (*SetLabelResponse, *http.Response, error) {
	return r.ApiService.ContentCoreOpenpgpUseridSetLabelExecute(r)
}

/*
ContentCoreOpenpgpUseridSetLabel Set a label

Set a single pulp_label on the object to a specific value or null.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param openPGPUserIDHref
 @return ContentOpenpgpUseridAPIContentCoreOpenpgpUseridSetLabelRequest
*/
func (a *ContentOpenpgpUseridAPIService) ContentCoreOpenpgpUseridSetLabel(ctx context.Context, openPGPUserIDHref string) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridSetLabelRequest {
	return ContentOpenpgpUseridAPIContentCoreOpenpgpUseridSetLabelRequest{
		ApiService: a,
		ctx: ctx,
		openPGPUserIDHref: openPGPUserIDHref,
	}
}

// Execute executes the request
//  @return SetLabelResponse
func (a *ContentOpenpgpUseridAPIService) ContentCoreOpenpgpUseridSetLabelExecute(r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridSetLabelRequest) (*SetLabelResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *SetLabelResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ContentOpenpgpUseridAPIService.ContentCoreOpenpgpUseridSetLabel")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/{open_p_g_p_user_i_d_href}set_label/"
	localVarPath = strings.Replace(localVarPath, "{"+"open_p_g_p_user_i_d_href"+"}", url.PathEscape(parameterValueToString(r.openPGPUserIDHref, "openPGPUserIDHref")), -1)
	localVarPath, _ = url.PathUnescape(localVarPath)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.setLabel == nil {
		return localVarReturnValue, nil, reportError("setLabel is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json", "application/x-www-form-urlencoded", "multipart/form-data"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xTaskDiagnostics != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Task-Diagnostics", r.xTaskDiagnostics, "simple", "csv")
	}
	// body params
	localVarPostBody = r.setLabel
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ContentOpenpgpUseridAPIContentCoreOpenpgpUseridUnsetLabelRequest struct {
	ctx context.Context
	ApiService *ContentOpenpgpUseridAPIService
	openPGPUserIDHref string
	unsetLabel *UnsetLabel
	xTaskDiagnostics *[]string
}

func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridUnsetLabelRequest) UnsetLabel(unsetLabel UnsetLabel) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridUnsetLabelRequest {
	r.unsetLabel = &unsetLabel
	return r
}

// List of profilers to use on tasks.
func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridUnsetLabelRequest) XTaskDiagnostics(xTaskDiagnostics []string) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridUnsetLabelRequest {
	r.xTaskDiagnostics = &xTaskDiagnostics
	return r
}

func (r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridUnsetLabelRequest) Execute() (*UnsetLabelResponse, *http.Response, error) {
	return r.ApiService.ContentCoreOpenpgpUseridUnsetLabelExecute(r)
}

/*
ContentCoreOpenpgpUseridUnsetLabel Unset a label

Unset a single pulp_label on the object.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param openPGPUserIDHref
 @return ContentOpenpgpUseridAPIContentCoreOpenpgpUseridUnsetLabelRequest
*/
func (a *ContentOpenpgpUseridAPIService) ContentCoreOpenpgpUseridUnsetLabel(ctx context.Context, openPGPUserIDHref string) ContentOpenpgpUseridAPIContentCoreOpenpgpUseridUnsetLabelRequest {
	return ContentOpenpgpUseridAPIContentCoreOpenpgpUseridUnsetLabelRequest{
		ApiService: a,
		ctx: ctx,
		openPGPUserIDHref: openPGPUserIDHref,
	}
}

// Execute executes the request
//  @return UnsetLabelResponse
func (a *ContentOpenpgpUseridAPIService) ContentCoreOpenpgpUseridUnsetLabelExecute(r ContentOpenpgpUseridAPIContentCoreOpenpgpUseridUnsetLabelRequest) (*UnsetLabelResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *UnsetLabelResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ContentOpenpgpUseridAPIService.ContentCoreOpenpgpUseridUnsetLabel")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/{open_p_g_p_user_i_d_href}unset_label/"
	localVarPath = strings.Replace(localVarPath, "{"+"open_p_g_p_user_i_d_href"+"}", url.PathEscape(parameterValueToString(r.openPGPUserIDHref, "openPGPUserIDHref")), -1)
	localVarPath, _ = url.PathUnescape(localVarPath)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.unsetLabel == nil {
		return localVarReturnValue, nil, reportError("unsetLabel is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json", "application/x-www-form-urlencoded", "multipart/form-data"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xTaskDiagnostics != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Task-Diagnostics", r.xTaskDiagnostics, "simple", "csv")
	}
	// body params
	localVarPostBody = r.unsetLabel
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
