/*
Pulp 3 API

Fetch, Upload, Organize, and Distribute Software Packages

API version: v3
Contact: pulp-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zest

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
	"reflect"
)


// ContentOpenpgpPublicsubkeyAPIService ContentOpenpgpPublicsubkeyAPI service
type ContentOpenpgpPublicsubkeyAPIService service

type ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest struct {
	ctx context.Context
	ApiService *ContentOpenpgpPublicsubkeyAPIService
	pulpDomain string
	xTaskDiagnostics *[]string
	fingerprint *string
	limit *int32
	offset *int32
	ordering *[]string
	orphanedFor *float32
	prnIn *[]string
	pulpHrefIn *[]string
	pulpIdIn *[]string
	pulpLabelSelect *string
	q *string
	repositoryVersion *string
	repositoryVersionAdded *string
	repositoryVersionRemoved *string
	fields *[]string
	excludeFields *[]string
}

// List of profilers to use on tasks.
func (r ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest) XTaskDiagnostics(xTaskDiagnostics []string) ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest {
	r.xTaskDiagnostics = &xTaskDiagnostics
	return r
}

// Filter results where fingerprint matches value
func (r ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest) Fingerprint(fingerprint string) ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest {
	r.fingerprint = &fingerprint
	return r
}

// Number of results to return per page.
func (r ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest) Limit(limit int32) ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest {
	r.limit = &limit
	return r
}

// The initial index from which to return the results.
func (r ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest) Offset(offset int32) ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest {
	r.offset = &offset
	return r
}

// Ordering* &#x60;pulp_id&#x60; - Pulp id* &#x60;-pulp_id&#x60; - Pulp id (descending)* &#x60;pulp_created&#x60; - Pulp created* &#x60;-pulp_created&#x60; - Pulp created (descending)* &#x60;pulp_last_updated&#x60; - Pulp last updated* &#x60;-pulp_last_updated&#x60; - Pulp last updated (descending)* &#x60;pulp_type&#x60; - Pulp type* &#x60;-pulp_type&#x60; - Pulp type (descending)* &#x60;upstream_id&#x60; - Upstream id* &#x60;-upstream_id&#x60; - Upstream id (descending)* &#x60;pulp_labels&#x60; - Pulp labels* &#x60;-pulp_labels&#x60; - Pulp labels (descending)* &#x60;timestamp_of_interest&#x60; - Timestamp of interest* &#x60;-timestamp_of_interest&#x60; - Timestamp of interest (descending)* &#x60;raw_data&#x60; - Raw data* &#x60;-raw_data&#x60; - Raw data (descending)* &#x60;fingerprint&#x60; - Fingerprint* &#x60;-fingerprint&#x60; - Fingerprint (descending)* &#x60;created&#x60; - Created* &#x60;-created&#x60; - Created (descending)* &#x60;pk&#x60; - Pk* &#x60;-pk&#x60; - Pk (descending)
func (r ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest) Ordering(ordering []string) ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest {
	r.ordering = &ordering
	return r
}

// Minutes Content has been orphaned for. -1 uses ORPHAN_PROTECTION_TIME.
func (r ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest) OrphanedFor(orphanedFor float32) ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest {
	r.orphanedFor = &orphanedFor
	return r
}

// Multiple values may be separated by commas.
func (r ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest) PrnIn(prnIn []string) ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest {
	r.prnIn = &prnIn
	return r
}

// Multiple values may be separated by commas.
func (r ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest) PulpHrefIn(pulpHrefIn []string) ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest {
	r.pulpHrefIn = &pulpHrefIn
	return r
}

// Multiple values may be separated by commas.
func (r ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest) PulpIdIn(pulpIdIn []string) ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest {
	r.pulpIdIn = &pulpIdIn
	return r
}

// Filter labels by search string
func (r ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest) PulpLabelSelect(pulpLabelSelect string) ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest {
	r.pulpLabelSelect = &pulpLabelSelect
	return r
}

// Filter results by using NOT, AND and OR operations on other filters
func (r ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest) Q(q string) ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest {
	r.q = &q
	return r
}

// Repository Version referenced by HREF/PRN
func (r ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest) RepositoryVersion(repositoryVersion string) ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest {
	r.repositoryVersion = &repositoryVersion
	return r
}

// Repository Version referenced by HREF/PRN
func (r ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest) RepositoryVersionAdded(repositoryVersionAdded string) ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest {
	r.repositoryVersionAdded = &repositoryVersionAdded
	return r
}

// Repository Version referenced by HREF/PRN
func (r ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest) RepositoryVersionRemoved(repositoryVersionRemoved string) ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest {
	r.repositoryVersionRemoved = &repositoryVersionRemoved
	return r
}

// A list of fields to include in the response.
func (r ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest) Fields(fields []string) ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest {
	r.fields = &fields
	return r
}

// A list of fields to exclude from the response.
func (r ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest) ExcludeFields(excludeFields []string) ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest {
	r.excludeFields = &excludeFields
	return r
}

func (r ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest) Execute() (*PaginatedOpenPGPPublicSubkeyResponseList, *http.Response, error) {
	return r.ApiService.ContentCoreOpenpgpPublicsubkeyListExecute(r)
}

/*
ContentCoreOpenpgpPublicsubkeyList List open pgp public subkeys

Content viewset that supports only GET by default.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param pulpDomain
 @return ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest
*/
func (a *ContentOpenpgpPublicsubkeyAPIService) ContentCoreOpenpgpPublicsubkeyList(ctx context.Context, pulpDomain string) ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest {
	return ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest{
		ApiService: a,
		ctx: ctx,
		pulpDomain: pulpDomain,
	}
}

// Execute executes the request
//  @return PaginatedOpenPGPPublicSubkeyResponseList
func (a *ContentOpenpgpPublicsubkeyAPIService) ContentCoreOpenpgpPublicsubkeyListExecute(r ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyListRequest) (*PaginatedOpenPGPPublicSubkeyResponseList, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *PaginatedOpenPGPPublicSubkeyResponseList
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ContentOpenpgpPublicsubkeyAPIService.ContentCoreOpenpgpPublicsubkeyList")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/pulp/{pulp_domain}/api/v3/content/core/openpgp_publicsubkey/"
	localVarPath = strings.Replace(localVarPath, "{"+"pulp_domain"+"}", url.PathEscape(parameterValueToString(r.pulpDomain, "pulpDomain")), -1)
	localVarPath, _ = url.PathUnescape(localVarPath)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.fingerprint != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "fingerprint", r.fingerprint, "form", "")
	}
	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	}
	if r.offset != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "offset", r.offset, "form", "")
	}
	if r.ordering != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "ordering", r.ordering, "form", "csv")
	}
	if r.orphanedFor != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "orphaned_for", r.orphanedFor, "form", "")
	}
	if r.prnIn != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "prn__in", r.prnIn, "form", "csv")
	}
	if r.pulpHrefIn != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "pulp_href__in", r.pulpHrefIn, "form", "csv")
	}
	if r.pulpIdIn != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "pulp_id__in", r.pulpIdIn, "form", "csv")
	}
	if r.pulpLabelSelect != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "pulp_label_select", r.pulpLabelSelect, "form", "")
	}
	if r.q != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "q", r.q, "form", "")
	}
	if r.repositoryVersion != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "repository_version", r.repositoryVersion, "form", "")
	}
	if r.repositoryVersionAdded != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "repository_version_added", r.repositoryVersionAdded, "form", "")
	}
	if r.repositoryVersionRemoved != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "repository_version_removed", r.repositoryVersionRemoved, "form", "")
	}
	if r.fields != nil {
		t := *r.fields
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
                               parameterAddToHeaderOrQuery(localVarQueryParams, "fields", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "fields", t, "form", "multi")
		}
	}
	if r.excludeFields != nil {
		t := *r.excludeFields
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
                               parameterAddToHeaderOrQuery(localVarQueryParams, "exclude_fields", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "exclude_fields", t, "form", "multi")
		}
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xTaskDiagnostics != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Task-Diagnostics", r.xTaskDiagnostics, "simple", "csv")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyReadRequest struct {
	ctx context.Context
	ApiService *ContentOpenpgpPublicsubkeyAPIService
	openPGPPublicSubkeyHref string
	xTaskDiagnostics *[]string
	fields *[]string
	excludeFields *[]string
}

// List of profilers to use on tasks.
func (r ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyReadRequest) XTaskDiagnostics(xTaskDiagnostics []string) ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyReadRequest {
	r.xTaskDiagnostics = &xTaskDiagnostics
	return r
}

// A list of fields to include in the response.
func (r ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyReadRequest) Fields(fields []string) ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyReadRequest {
	r.fields = &fields
	return r
}

// A list of fields to exclude from the response.
func (r ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyReadRequest) ExcludeFields(excludeFields []string) ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyReadRequest {
	r.excludeFields = &excludeFields
	return r
}

func (r ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyReadRequest) Execute() (*OpenPGPPublicSubkeyResponse, *http.Response, error) {
	return r.ApiService.ContentCoreOpenpgpPublicsubkeyReadExecute(r)
}

/*
ContentCoreOpenpgpPublicsubkeyRead Inspect an open pgp public subkey

Content viewset that supports only GET by default.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param openPGPPublicSubkeyHref
 @return ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyReadRequest
*/
func (a *ContentOpenpgpPublicsubkeyAPIService) ContentCoreOpenpgpPublicsubkeyRead(ctx context.Context, openPGPPublicSubkeyHref string) ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyReadRequest {
	return ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyReadRequest{
		ApiService: a,
		ctx: ctx,
		openPGPPublicSubkeyHref: openPGPPublicSubkeyHref,
	}
}

// Execute executes the request
//  @return OpenPGPPublicSubkeyResponse
func (a *ContentOpenpgpPublicsubkeyAPIService) ContentCoreOpenpgpPublicsubkeyReadExecute(r ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyReadRequest) (*OpenPGPPublicSubkeyResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *OpenPGPPublicSubkeyResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ContentOpenpgpPublicsubkeyAPIService.ContentCoreOpenpgpPublicsubkeyRead")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/{open_p_g_p_public_subkey_href}"
	localVarPath = strings.Replace(localVarPath, "{"+"open_p_g_p_public_subkey_href"+"}", url.PathEscape(parameterValueToString(r.openPGPPublicSubkeyHref, "openPGPPublicSubkeyHref")), -1)
	localVarPath, _ = url.PathUnescape(localVarPath)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.fields != nil {
		t := *r.fields
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
                               parameterAddToHeaderOrQuery(localVarQueryParams, "fields", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "fields", t, "form", "multi")
		}
	}
	if r.excludeFields != nil {
		t := *r.excludeFields
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
                               parameterAddToHeaderOrQuery(localVarQueryParams, "exclude_fields", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "exclude_fields", t, "form", "multi")
		}
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xTaskDiagnostics != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Task-Diagnostics", r.xTaskDiagnostics, "simple", "csv")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeySetLabelRequest struct {
	ctx context.Context
	ApiService *ContentOpenpgpPublicsubkeyAPIService
	openPGPPublicSubkeyHref string
	setLabel *SetLabel
	xTaskDiagnostics *[]string
}

func (r ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeySetLabelRequest) SetLabel(setLabel SetLabel) ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeySetLabelRequest {
	r.setLabel = &setLabel
	return r
}

// List of profilers to use on tasks.
func (r ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeySetLabelRequest) XTaskDiagnostics(xTaskDiagnostics []string) ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeySetLabelRequest {
	r.xTaskDiagnostics = &xTaskDiagnostics
	return r
}

func (r ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeySetLabelRequest) Execute() (*SetLabelResponse, *http.Response, error) {
	return r.ApiService.ContentCoreOpenpgpPublicsubkeySetLabelExecute(r)
}

/*
ContentCoreOpenpgpPublicsubkeySetLabel Set a label

Set a single pulp_label on the object to a specific value or null.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param openPGPPublicSubkeyHref
 @return ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeySetLabelRequest
*/
func (a *ContentOpenpgpPublicsubkeyAPIService) ContentCoreOpenpgpPublicsubkeySetLabel(ctx context.Context, openPGPPublicSubkeyHref string) ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeySetLabelRequest {
	return ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeySetLabelRequest{
		ApiService: a,
		ctx: ctx,
		openPGPPublicSubkeyHref: openPGPPublicSubkeyHref,
	}
}

// Execute executes the request
//  @return SetLabelResponse
func (a *ContentOpenpgpPublicsubkeyAPIService) ContentCoreOpenpgpPublicsubkeySetLabelExecute(r ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeySetLabelRequest) (*SetLabelResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *SetLabelResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ContentOpenpgpPublicsubkeyAPIService.ContentCoreOpenpgpPublicsubkeySetLabel")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/{open_p_g_p_public_subkey_href}set_label/"
	localVarPath = strings.Replace(localVarPath, "{"+"open_p_g_p_public_subkey_href"+"}", url.PathEscape(parameterValueToString(r.openPGPPublicSubkeyHref, "openPGPPublicSubkeyHref")), -1)
	localVarPath, _ = url.PathUnescape(localVarPath)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.setLabel == nil {
		return localVarReturnValue, nil, reportError("setLabel is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json", "application/x-www-form-urlencoded", "multipart/form-data"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xTaskDiagnostics != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Task-Diagnostics", r.xTaskDiagnostics, "simple", "csv")
	}
	// body params
	localVarPostBody = r.setLabel
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyUnsetLabelRequest struct {
	ctx context.Context
	ApiService *ContentOpenpgpPublicsubkeyAPIService
	openPGPPublicSubkeyHref string
	unsetLabel *UnsetLabel
	xTaskDiagnostics *[]string
}

func (r ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyUnsetLabelRequest) UnsetLabel(unsetLabel UnsetLabel) ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyUnsetLabelRequest {
	r.unsetLabel = &unsetLabel
	return r
}

// List of profilers to use on tasks.
func (r ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyUnsetLabelRequest) XTaskDiagnostics(xTaskDiagnostics []string) ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyUnsetLabelRequest {
	r.xTaskDiagnostics = &xTaskDiagnostics
	return r
}

func (r ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyUnsetLabelRequest) Execute() (*UnsetLabelResponse, *http.Response, error) {
	return r.ApiService.ContentCoreOpenpgpPublicsubkeyUnsetLabelExecute(r)
}

/*
ContentCoreOpenpgpPublicsubkeyUnsetLabel Unset a label

Unset a single pulp_label on the object.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param openPGPPublicSubkeyHref
 @return ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyUnsetLabelRequest
*/
func (a *ContentOpenpgpPublicsubkeyAPIService) ContentCoreOpenpgpPublicsubkeyUnsetLabel(ctx context.Context, openPGPPublicSubkeyHref string) ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyUnsetLabelRequest {
	return ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyUnsetLabelRequest{
		ApiService: a,
		ctx: ctx,
		openPGPPublicSubkeyHref: openPGPPublicSubkeyHref,
	}
}

// Execute executes the request
//  @return UnsetLabelResponse
func (a *ContentOpenpgpPublicsubkeyAPIService) ContentCoreOpenpgpPublicsubkeyUnsetLabelExecute(r ContentOpenpgpPublicsubkeyAPIContentCoreOpenpgpPublicsubkeyUnsetLabelRequest) (*UnsetLabelResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *UnsetLabelResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ContentOpenpgpPublicsubkeyAPIService.ContentCoreOpenpgpPublicsubkeyUnsetLabel")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/{open_p_g_p_public_subkey_href}unset_label/"
	localVarPath = strings.Replace(localVarPath, "{"+"open_p_g_p_public_subkey_href"+"}", url.PathEscape(parameterValueToString(r.openPGPPublicSubkeyHref, "openPGPPublicSubkeyHref")), -1)
	localVarPath, _ = url.PathUnescape(localVarPath)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.unsetLabel == nil {
		return localVarReturnValue, nil, reportError("unsetLabel is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json", "application/x-www-form-urlencoded", "multipart/form-data"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xTaskDiagnostics != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Task-Diagnostics", r.xTaskDiagnostics, "simple", "csv")
	}
	// body params
	localVarPostBody = r.unsetLabel
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
