/*
Pulp 3 API

Fetch, Upload, Organize, and Distribute Software Packages

API version: v3
Contact: pulp-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zest

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the OpenPGPSignatureResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenPGPSignatureResponse{}

// OpenPGPSignatureResponse Base serializer for use with [pulpcore.app.models.Model][]This ensures that all Serializers provide values for the 'pulp_href` field.The class provides a default for the ``ref_name`` attribute in theModelSerializers's ``Meta`` class. This ensures that the OpenAPI definitionsof plugins are namespaced properly.
type OpenPGPSignatureResponse struct {
	PulpHref *string `json:"pulp_href,omitempty"`
	// The Pulp Resource Name (PRN).
	Prn *string `json:"prn,omitempty"`
	// Timestamp of creation.
	PulpCreated *time.Time `json:"pulp_created,omitempty"`
	// Timestamp of the last time this resource was updated. Note: for immutable resources - like content, repository versions, and publication - pulp_created and pulp_last_updated dates will be the same.
	PulpLastUpdated *time.Time `json:"pulp_last_updated,omitempty"`
	// A dictionary of arbitrary key/value pairs used to describe a specific Content instance.
	PulpLabels *map[string]string `json:"pulp_labels,omitempty"`
	VulnReport *string `json:"vuln_report,omitempty"`
	Issuer NullableString `json:"issuer,omitempty"`
	Created time.Time `json:"created"`
	ExpirationTime NullableString `json:"expiration_time,omitempty"`
	SignersUserId NullableString `json:"signers_user_id,omitempty"`
	KeyExpirationTime NullableString `json:"key_expiration_time,omitempty"`
	Expired bool `json:"expired"`
	KeyExpired *string `json:"key_expired,omitempty"`
	SignedContent *string `json:"signed_content,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _OpenPGPSignatureResponse OpenPGPSignatureResponse

// NewOpenPGPSignatureResponse instantiates a new OpenPGPSignatureResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenPGPSignatureResponse(created time.Time, expired bool) *OpenPGPSignatureResponse {
	this := OpenPGPSignatureResponse{}
	this.Created = created
	this.Expired = expired
	return &this
}

// NewOpenPGPSignatureResponseWithDefaults instantiates a new OpenPGPSignatureResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenPGPSignatureResponseWithDefaults() *OpenPGPSignatureResponse {
	this := OpenPGPSignatureResponse{}
	return &this
}

// GetPulpHref returns the PulpHref field value if set, zero value otherwise.
func (o *OpenPGPSignatureResponse) GetPulpHref() string {
	if o == nil || IsNil(o.PulpHref) {
		var ret string
		return ret
	}
	return *o.PulpHref
}

// GetPulpHrefOk returns a tuple with the PulpHref field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenPGPSignatureResponse) GetPulpHrefOk() (*string, bool) {
	if o == nil || IsNil(o.PulpHref) {
		return nil, false
	}
	return o.PulpHref, true
}

// HasPulpHref returns a boolean if a field has been set.
func (o *OpenPGPSignatureResponse) HasPulpHref() bool {
	if o != nil && !IsNil(o.PulpHref) {
		return true
	}

	return false
}

// SetPulpHref gets a reference to the given string and assigns it to the PulpHref field.
func (o *OpenPGPSignatureResponse) SetPulpHref(v string) {
	o.PulpHref = &v
}

// GetPrn returns the Prn field value if set, zero value otherwise.
func (o *OpenPGPSignatureResponse) GetPrn() string {
	if o == nil || IsNil(o.Prn) {
		var ret string
		return ret
	}
	return *o.Prn
}

// GetPrnOk returns a tuple with the Prn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenPGPSignatureResponse) GetPrnOk() (*string, bool) {
	if o == nil || IsNil(o.Prn) {
		return nil, false
	}
	return o.Prn, true
}

// HasPrn returns a boolean if a field has been set.
func (o *OpenPGPSignatureResponse) HasPrn() bool {
	if o != nil && !IsNil(o.Prn) {
		return true
	}

	return false
}

// SetPrn gets a reference to the given string and assigns it to the Prn field.
func (o *OpenPGPSignatureResponse) SetPrn(v string) {
	o.Prn = &v
}

// GetPulpCreated returns the PulpCreated field value if set, zero value otherwise.
func (o *OpenPGPSignatureResponse) GetPulpCreated() time.Time {
	if o == nil || IsNil(o.PulpCreated) {
		var ret time.Time
		return ret
	}
	return *o.PulpCreated
}

// GetPulpCreatedOk returns a tuple with the PulpCreated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenPGPSignatureResponse) GetPulpCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.PulpCreated) {
		return nil, false
	}
	return o.PulpCreated, true
}

// HasPulpCreated returns a boolean if a field has been set.
func (o *OpenPGPSignatureResponse) HasPulpCreated() bool {
	if o != nil && !IsNil(o.PulpCreated) {
		return true
	}

	return false
}

// SetPulpCreated gets a reference to the given time.Time and assigns it to the PulpCreated field.
func (o *OpenPGPSignatureResponse) SetPulpCreated(v time.Time) {
	o.PulpCreated = &v
}

// GetPulpLastUpdated returns the PulpLastUpdated field value if set, zero value otherwise.
func (o *OpenPGPSignatureResponse) GetPulpLastUpdated() time.Time {
	if o == nil || IsNil(o.PulpLastUpdated) {
		var ret time.Time
		return ret
	}
	return *o.PulpLastUpdated
}

// GetPulpLastUpdatedOk returns a tuple with the PulpLastUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenPGPSignatureResponse) GetPulpLastUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.PulpLastUpdated) {
		return nil, false
	}
	return o.PulpLastUpdated, true
}

// HasPulpLastUpdated returns a boolean if a field has been set.
func (o *OpenPGPSignatureResponse) HasPulpLastUpdated() bool {
	if o != nil && !IsNil(o.PulpLastUpdated) {
		return true
	}

	return false
}

// SetPulpLastUpdated gets a reference to the given time.Time and assigns it to the PulpLastUpdated field.
func (o *OpenPGPSignatureResponse) SetPulpLastUpdated(v time.Time) {
	o.PulpLastUpdated = &v
}

// GetPulpLabels returns the PulpLabels field value if set, zero value otherwise.
func (o *OpenPGPSignatureResponse) GetPulpLabels() map[string]string {
	if o == nil || IsNil(o.PulpLabels) {
		var ret map[string]string
		return ret
	}
	return *o.PulpLabels
}

// GetPulpLabelsOk returns a tuple with the PulpLabels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenPGPSignatureResponse) GetPulpLabelsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.PulpLabels) {
		return nil, false
	}
	return o.PulpLabels, true
}

// HasPulpLabels returns a boolean if a field has been set.
func (o *OpenPGPSignatureResponse) HasPulpLabels() bool {
	if o != nil && !IsNil(o.PulpLabels) {
		return true
	}

	return false
}

// SetPulpLabels gets a reference to the given map[string]string and assigns it to the PulpLabels field.
func (o *OpenPGPSignatureResponse) SetPulpLabels(v map[string]string) {
	o.PulpLabels = &v
}

// GetVulnReport returns the VulnReport field value if set, zero value otherwise.
func (o *OpenPGPSignatureResponse) GetVulnReport() string {
	if o == nil || IsNil(o.VulnReport) {
		var ret string
		return ret
	}
	return *o.VulnReport
}

// GetVulnReportOk returns a tuple with the VulnReport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenPGPSignatureResponse) GetVulnReportOk() (*string, bool) {
	if o == nil || IsNil(o.VulnReport) {
		return nil, false
	}
	return o.VulnReport, true
}

// HasVulnReport returns a boolean if a field has been set.
func (o *OpenPGPSignatureResponse) HasVulnReport() bool {
	if o != nil && !IsNil(o.VulnReport) {
		return true
	}

	return false
}

// SetVulnReport gets a reference to the given string and assigns it to the VulnReport field.
func (o *OpenPGPSignatureResponse) SetVulnReport(v string) {
	o.VulnReport = &v
}

// GetIssuer returns the Issuer field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenPGPSignatureResponse) GetIssuer() string {
	if o == nil || IsNil(o.Issuer.Get()) {
		var ret string
		return ret
	}
	return *o.Issuer.Get()
}

// GetIssuerOk returns a tuple with the Issuer field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenPGPSignatureResponse) GetIssuerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Issuer.Get(), o.Issuer.IsSet()
}

// HasIssuer returns a boolean if a field has been set.
func (o *OpenPGPSignatureResponse) HasIssuer() bool {
	if o != nil && o.Issuer.IsSet() {
		return true
	}

	return false
}

// SetIssuer gets a reference to the given NullableString and assigns it to the Issuer field.
func (o *OpenPGPSignatureResponse) SetIssuer(v string) {
	o.Issuer.Set(&v)
}
// SetIssuerNil sets the value for Issuer to be an explicit nil
func (o *OpenPGPSignatureResponse) SetIssuerNil() {
	o.Issuer.Set(nil)
}

// UnsetIssuer ensures that no value is present for Issuer, not even an explicit nil
func (o *OpenPGPSignatureResponse) UnsetIssuer() {
	o.Issuer.Unset()
}

// GetCreated returns the Created field value
func (o *OpenPGPSignatureResponse) GetCreated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *OpenPGPSignatureResponse) GetCreatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *OpenPGPSignatureResponse) SetCreated(v time.Time) {
	o.Created = v
}

// GetExpirationTime returns the ExpirationTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenPGPSignatureResponse) GetExpirationTime() string {
	if o == nil || IsNil(o.ExpirationTime.Get()) {
		var ret string
		return ret
	}
	return *o.ExpirationTime.Get()
}

// GetExpirationTimeOk returns a tuple with the ExpirationTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenPGPSignatureResponse) GetExpirationTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpirationTime.Get(), o.ExpirationTime.IsSet()
}

// HasExpirationTime returns a boolean if a field has been set.
func (o *OpenPGPSignatureResponse) HasExpirationTime() bool {
	if o != nil && o.ExpirationTime.IsSet() {
		return true
	}

	return false
}

// SetExpirationTime gets a reference to the given NullableString and assigns it to the ExpirationTime field.
func (o *OpenPGPSignatureResponse) SetExpirationTime(v string) {
	o.ExpirationTime.Set(&v)
}
// SetExpirationTimeNil sets the value for ExpirationTime to be an explicit nil
func (o *OpenPGPSignatureResponse) SetExpirationTimeNil() {
	o.ExpirationTime.Set(nil)
}

// UnsetExpirationTime ensures that no value is present for ExpirationTime, not even an explicit nil
func (o *OpenPGPSignatureResponse) UnsetExpirationTime() {
	o.ExpirationTime.Unset()
}

// GetSignersUserId returns the SignersUserId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenPGPSignatureResponse) GetSignersUserId() string {
	if o == nil || IsNil(o.SignersUserId.Get()) {
		var ret string
		return ret
	}
	return *o.SignersUserId.Get()
}

// GetSignersUserIdOk returns a tuple with the SignersUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenPGPSignatureResponse) GetSignersUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SignersUserId.Get(), o.SignersUserId.IsSet()
}

// HasSignersUserId returns a boolean if a field has been set.
func (o *OpenPGPSignatureResponse) HasSignersUserId() bool {
	if o != nil && o.SignersUserId.IsSet() {
		return true
	}

	return false
}

// SetSignersUserId gets a reference to the given NullableString and assigns it to the SignersUserId field.
func (o *OpenPGPSignatureResponse) SetSignersUserId(v string) {
	o.SignersUserId.Set(&v)
}
// SetSignersUserIdNil sets the value for SignersUserId to be an explicit nil
func (o *OpenPGPSignatureResponse) SetSignersUserIdNil() {
	o.SignersUserId.Set(nil)
}

// UnsetSignersUserId ensures that no value is present for SignersUserId, not even an explicit nil
func (o *OpenPGPSignatureResponse) UnsetSignersUserId() {
	o.SignersUserId.Unset()
}

// GetKeyExpirationTime returns the KeyExpirationTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenPGPSignatureResponse) GetKeyExpirationTime() string {
	if o == nil || IsNil(o.KeyExpirationTime.Get()) {
		var ret string
		return ret
	}
	return *o.KeyExpirationTime.Get()
}

// GetKeyExpirationTimeOk returns a tuple with the KeyExpirationTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenPGPSignatureResponse) GetKeyExpirationTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.KeyExpirationTime.Get(), o.KeyExpirationTime.IsSet()
}

// HasKeyExpirationTime returns a boolean if a field has been set.
func (o *OpenPGPSignatureResponse) HasKeyExpirationTime() bool {
	if o != nil && o.KeyExpirationTime.IsSet() {
		return true
	}

	return false
}

// SetKeyExpirationTime gets a reference to the given NullableString and assigns it to the KeyExpirationTime field.
func (o *OpenPGPSignatureResponse) SetKeyExpirationTime(v string) {
	o.KeyExpirationTime.Set(&v)
}
// SetKeyExpirationTimeNil sets the value for KeyExpirationTime to be an explicit nil
func (o *OpenPGPSignatureResponse) SetKeyExpirationTimeNil() {
	o.KeyExpirationTime.Set(nil)
}

// UnsetKeyExpirationTime ensures that no value is present for KeyExpirationTime, not even an explicit nil
func (o *OpenPGPSignatureResponse) UnsetKeyExpirationTime() {
	o.KeyExpirationTime.Unset()
}

// GetExpired returns the Expired field value
func (o *OpenPGPSignatureResponse) GetExpired() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Expired
}

// GetExpiredOk returns a tuple with the Expired field value
// and a boolean to check if the value has been set.
func (o *OpenPGPSignatureResponse) GetExpiredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Expired, true
}

// SetExpired sets field value
func (o *OpenPGPSignatureResponse) SetExpired(v bool) {
	o.Expired = v
}

// GetKeyExpired returns the KeyExpired field value if set, zero value otherwise.
func (o *OpenPGPSignatureResponse) GetKeyExpired() string {
	if o == nil || IsNil(o.KeyExpired) {
		var ret string
		return ret
	}
	return *o.KeyExpired
}

// GetKeyExpiredOk returns a tuple with the KeyExpired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenPGPSignatureResponse) GetKeyExpiredOk() (*string, bool) {
	if o == nil || IsNil(o.KeyExpired) {
		return nil, false
	}
	return o.KeyExpired, true
}

// HasKeyExpired returns a boolean if a field has been set.
func (o *OpenPGPSignatureResponse) HasKeyExpired() bool {
	if o != nil && !IsNil(o.KeyExpired) {
		return true
	}

	return false
}

// SetKeyExpired gets a reference to the given string and assigns it to the KeyExpired field.
func (o *OpenPGPSignatureResponse) SetKeyExpired(v string) {
	o.KeyExpired = &v
}

// GetSignedContent returns the SignedContent field value if set, zero value otherwise.
func (o *OpenPGPSignatureResponse) GetSignedContent() string {
	if o == nil || IsNil(o.SignedContent) {
		var ret string
		return ret
	}
	return *o.SignedContent
}

// GetSignedContentOk returns a tuple with the SignedContent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenPGPSignatureResponse) GetSignedContentOk() (*string, bool) {
	if o == nil || IsNil(o.SignedContent) {
		return nil, false
	}
	return o.SignedContent, true
}

// HasSignedContent returns a boolean if a field has been set.
func (o *OpenPGPSignatureResponse) HasSignedContent() bool {
	if o != nil && !IsNil(o.SignedContent) {
		return true
	}

	return false
}

// SetSignedContent gets a reference to the given string and assigns it to the SignedContent field.
func (o *OpenPGPSignatureResponse) SetSignedContent(v string) {
	o.SignedContent = &v
}

func (o OpenPGPSignatureResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenPGPSignatureResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PulpHref) {
		toSerialize["pulp_href"] = o.PulpHref
	}
	if !IsNil(o.Prn) {
		toSerialize["prn"] = o.Prn
	}
	if !IsNil(o.PulpCreated) {
		toSerialize["pulp_created"] = o.PulpCreated
	}
	if !IsNil(o.PulpLastUpdated) {
		toSerialize["pulp_last_updated"] = o.PulpLastUpdated
	}
	if !IsNil(o.PulpLabels) {
		toSerialize["pulp_labels"] = o.PulpLabels
	}
	if !IsNil(o.VulnReport) {
		toSerialize["vuln_report"] = o.VulnReport
	}
	if o.Issuer.IsSet() {
		toSerialize["issuer"] = o.Issuer.Get()
	}
	toSerialize["created"] = o.Created
	if o.ExpirationTime.IsSet() {
		toSerialize["expiration_time"] = o.ExpirationTime.Get()
	}
	if o.SignersUserId.IsSet() {
		toSerialize["signers_user_id"] = o.SignersUserId.Get()
	}
	if o.KeyExpirationTime.IsSet() {
		toSerialize["key_expiration_time"] = o.KeyExpirationTime.Get()
	}
	toSerialize["expired"] = o.Expired
	if !IsNil(o.KeyExpired) {
		toSerialize["key_expired"] = o.KeyExpired
	}
	if !IsNil(o.SignedContent) {
		toSerialize["signed_content"] = o.SignedContent
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OpenPGPSignatureResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created",
		"expired",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOpenPGPSignatureResponse := _OpenPGPSignatureResponse{}

	err = json.Unmarshal(data, &varOpenPGPSignatureResponse)

	if err != nil {
		return err
	}

	*o = OpenPGPSignatureResponse(varOpenPGPSignatureResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "pulp_href")
		delete(additionalProperties, "prn")
		delete(additionalProperties, "pulp_created")
		delete(additionalProperties, "pulp_last_updated")
		delete(additionalProperties, "pulp_labels")
		delete(additionalProperties, "vuln_report")
		delete(additionalProperties, "issuer")
		delete(additionalProperties, "created")
		delete(additionalProperties, "expiration_time")
		delete(additionalProperties, "signers_user_id")
		delete(additionalProperties, "key_expiration_time")
		delete(additionalProperties, "expired")
		delete(additionalProperties, "key_expired")
		delete(additionalProperties, "signed_content")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOpenPGPSignatureResponse struct {
	value *OpenPGPSignatureResponse
	isSet bool
}

func (v NullableOpenPGPSignatureResponse) Get() *OpenPGPSignatureResponse {
	return v.value
}

func (v *NullableOpenPGPSignatureResponse) Set(val *OpenPGPSignatureResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenPGPSignatureResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenPGPSignatureResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenPGPSignatureResponse(val *OpenPGPSignatureResponse) *NullableOpenPGPSignatureResponse {
	return &NullableOpenPGPSignatureResponse{value: val, isSet: true}
}

func (v NullableOpenPGPSignatureResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenPGPSignatureResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


