/*
Pulp 3 API

Fetch, Upload, Organize, and Distribute Software Packages

API version: v3
Contact: pulp-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zest

import (
	"encoding/json"
	"time"
)

// checks if the AppStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppStatusResponse{}

// AppStatusResponse struct for AppStatusResponse
type AppStatusResponse struct {
	// The name of the worker.
	Name *string `json:"name,omitempty"`
	// Timestamp of the last time the worker talked to the service.
	LastHeartbeat *time.Time `json:"last_heartbeat,omitempty"`
	// Versions of the components installed.
	Versions *map[string]string `json:"versions,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AppStatusResponse AppStatusResponse

// NewAppStatusResponse instantiates a new AppStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppStatusResponse() *AppStatusResponse {
	this := AppStatusResponse{}
	return &this
}

// NewAppStatusResponseWithDefaults instantiates a new AppStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppStatusResponseWithDefaults() *AppStatusResponse {
	this := AppStatusResponse{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AppStatusResponse) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppStatusResponse) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AppStatusResponse) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AppStatusResponse) SetName(v string) {
	o.Name = &v
}

// GetLastHeartbeat returns the LastHeartbeat field value if set, zero value otherwise.
func (o *AppStatusResponse) GetLastHeartbeat() time.Time {
	if o == nil || IsNil(o.LastHeartbeat) {
		var ret time.Time
		return ret
	}
	return *o.LastHeartbeat
}

// GetLastHeartbeatOk returns a tuple with the LastHeartbeat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppStatusResponse) GetLastHeartbeatOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastHeartbeat) {
		return nil, false
	}
	return o.LastHeartbeat, true
}

// HasLastHeartbeat returns a boolean if a field has been set.
func (o *AppStatusResponse) HasLastHeartbeat() bool {
	if o != nil && !IsNil(o.LastHeartbeat) {
		return true
	}

	return false
}

// SetLastHeartbeat gets a reference to the given time.Time and assigns it to the LastHeartbeat field.
func (o *AppStatusResponse) SetLastHeartbeat(v time.Time) {
	o.LastHeartbeat = &v
}

// GetVersions returns the Versions field value if set, zero value otherwise.
func (o *AppStatusResponse) GetVersions() map[string]string {
	if o == nil || IsNil(o.Versions) {
		var ret map[string]string
		return ret
	}
	return *o.Versions
}

// GetVersionsOk returns a tuple with the Versions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppStatusResponse) GetVersionsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Versions) {
		return nil, false
	}
	return o.Versions, true
}

// HasVersions returns a boolean if a field has been set.
func (o *AppStatusResponse) HasVersions() bool {
	if o != nil && !IsNil(o.Versions) {
		return true
	}

	return false
}

// SetVersions gets a reference to the given map[string]string and assigns it to the Versions field.
func (o *AppStatusResponse) SetVersions(v map[string]string) {
	o.Versions = &v
}

func (o AppStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.LastHeartbeat) {
		toSerialize["last_heartbeat"] = o.LastHeartbeat
	}
	if !IsNil(o.Versions) {
		toSerialize["versions"] = o.Versions
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AppStatusResponse) UnmarshalJSON(data []byte) (err error) {
	varAppStatusResponse := _AppStatusResponse{}

	err = json.Unmarshal(data, &varAppStatusResponse)

	if err != nil {
		return err
	}

	*o = AppStatusResponse(varAppStatusResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "last_heartbeat")
		delete(additionalProperties, "versions")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAppStatusResponse struct {
	value *AppStatusResponse
	isSet bool
}

func (v NullableAppStatusResponse) Get() *AppStatusResponse {
	return v.value
}

func (v *NullableAppStatusResponse) Set(val *AppStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAppStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAppStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppStatusResponse(val *AppStatusResponse) *NullableAppStatusResponse {
	return &NullableAppStatusResponse{value: val, isSet: true}
}

func (v NullableAppStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


