/*
Pulp 3 API

Fetch, Upload, Organize, and Distribute Software Packages

API version: v3
Contact: pulp-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zest

import (
	"encoding/json"
	"fmt"
)

// checks if the RpmRpmRepository type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RpmRpmRepository{}

// RpmRpmRepository Serializer for Rpm Repositories.
type RpmRpmRepository struct {
	PulpLabels *map[string]string `json:"pulp_labels,omitempty"`
	// A unique name for this repository.
	Name string `json:"name"`
	// An optional description.
	Description NullableString `json:"description,omitempty"`
	// Retain X versions of the repository. Default is null which retains all versions.
	RetainRepoVersions NullableInt64 `json:"retain_repo_versions,omitempty"`
	// An optional remote to use by default when syncing.
	Remote NullableString `json:"remote,omitempty"`
	// Whether to automatically create publications for new repository versions, and update any distributions pointing to this repository.
	Autopublish *bool `json:"autopublish,omitempty"`
	// A reference to an associated signing service.
	MetadataSigningService NullableString `json:"metadata_signing_service,omitempty"`
	// A reference to an associated package signing service.
	PackageSigningService NullableString `json:"package_signing_service,omitempty"`
	// The pubkey V4 fingerprint (160 bits) to be passed to the package signing service.The signing service will use that on signing operations related to this repository.
	PackageSigningFingerprint *string `json:"package_signing_fingerprint,omitempty"`
	// The number of versions of each package to keep in the repository; older versions will be purged. The default is '0', which will disable this feature and keep all versions of each package.
	RetainPackageVersions *int64 `json:"retain_package_versions,omitempty"`
	// The preferred checksum type during repo publish.* `unknown` - unknown* `md5` - md5* `sha1` - sha1* `sha224` - sha224* `sha256` - sha256* `sha384` - sha384* `sha512` - sha512
	ChecksumType NullablePackageChecksumTypeEnum `json:"checksum_type,omitempty"`
	// A JSON document describing the config.repo file Pulp should generate for this repo
	RepoConfig interface{} `json:"repo_config,omitempty"`
	// The compression type to use for metadata files.* `zstd` - zstd* `gz` - gz* `none` - none
	CompressionType NullableCompressionTypeEnum `json:"compression_type,omitempty"`
	// How to layout the packages within the published repository.* `nested_alphabetically` - nested_alphabetically* `flat` - flat* `nested_by_digest` - nested_by_digest* `nested_by_both` - nested_by_both
	Layout NullableLayoutEnum `json:"layout,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RpmRpmRepository RpmRpmRepository

// NewRpmRpmRepository instantiates a new RpmRpmRepository object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRpmRpmRepository(name string) *RpmRpmRepository {
	this := RpmRpmRepository{}
	this.Name = name
	var autopublish bool = false
	this.Autopublish = &autopublish
	var packageSigningFingerprint string = ""
	this.PackageSigningFingerprint = &packageSigningFingerprint
	return &this
}

// NewRpmRpmRepositoryWithDefaults instantiates a new RpmRpmRepository object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRpmRpmRepositoryWithDefaults() *RpmRpmRepository {
	this := RpmRpmRepository{}
	var autopublish bool = false
	this.Autopublish = &autopublish
	var packageSigningFingerprint string = ""
	this.PackageSigningFingerprint = &packageSigningFingerprint
	return &this
}

// GetPulpLabels returns the PulpLabels field value if set, zero value otherwise.
func (o *RpmRpmRepository) GetPulpLabels() map[string]string {
	if o == nil || IsNil(o.PulpLabels) {
		var ret map[string]string
		return ret
	}
	return *o.PulpLabels
}

// GetPulpLabelsOk returns a tuple with the PulpLabels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpmRpmRepository) GetPulpLabelsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.PulpLabels) {
		return nil, false
	}
	return o.PulpLabels, true
}

// HasPulpLabels returns a boolean if a field has been set.
func (o *RpmRpmRepository) HasPulpLabels() bool {
	if o != nil && !IsNil(o.PulpLabels) {
		return true
	}

	return false
}

// SetPulpLabels gets a reference to the given map[string]string and assigns it to the PulpLabels field.
func (o *RpmRpmRepository) SetPulpLabels(v map[string]string) {
	o.PulpLabels = &v
}

// GetName returns the Name field value
func (o *RpmRpmRepository) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *RpmRpmRepository) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *RpmRpmRepository) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RpmRpmRepository) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RpmRpmRepository) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *RpmRpmRepository) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *RpmRpmRepository) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *RpmRpmRepository) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *RpmRpmRepository) UnsetDescription() {
	o.Description.Unset()
}

// GetRetainRepoVersions returns the RetainRepoVersions field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RpmRpmRepository) GetRetainRepoVersions() int64 {
	if o == nil || IsNil(o.RetainRepoVersions.Get()) {
		var ret int64
		return ret
	}
	return *o.RetainRepoVersions.Get()
}

// GetRetainRepoVersionsOk returns a tuple with the RetainRepoVersions field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RpmRpmRepository) GetRetainRepoVersionsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.RetainRepoVersions.Get(), o.RetainRepoVersions.IsSet()
}

// HasRetainRepoVersions returns a boolean if a field has been set.
func (o *RpmRpmRepository) HasRetainRepoVersions() bool {
	if o != nil && o.RetainRepoVersions.IsSet() {
		return true
	}

	return false
}

// SetRetainRepoVersions gets a reference to the given NullableInt64 and assigns it to the RetainRepoVersions field.
func (o *RpmRpmRepository) SetRetainRepoVersions(v int64) {
	o.RetainRepoVersions.Set(&v)
}
// SetRetainRepoVersionsNil sets the value for RetainRepoVersions to be an explicit nil
func (o *RpmRpmRepository) SetRetainRepoVersionsNil() {
	o.RetainRepoVersions.Set(nil)
}

// UnsetRetainRepoVersions ensures that no value is present for RetainRepoVersions, not even an explicit nil
func (o *RpmRpmRepository) UnsetRetainRepoVersions() {
	o.RetainRepoVersions.Unset()
}

// GetRemote returns the Remote field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RpmRpmRepository) GetRemote() string {
	if o == nil || IsNil(o.Remote.Get()) {
		var ret string
		return ret
	}
	return *o.Remote.Get()
}

// GetRemoteOk returns a tuple with the Remote field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RpmRpmRepository) GetRemoteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Remote.Get(), o.Remote.IsSet()
}

// HasRemote returns a boolean if a field has been set.
func (o *RpmRpmRepository) HasRemote() bool {
	if o != nil && o.Remote.IsSet() {
		return true
	}

	return false
}

// SetRemote gets a reference to the given NullableString and assigns it to the Remote field.
func (o *RpmRpmRepository) SetRemote(v string) {
	o.Remote.Set(&v)
}
// SetRemoteNil sets the value for Remote to be an explicit nil
func (o *RpmRpmRepository) SetRemoteNil() {
	o.Remote.Set(nil)
}

// UnsetRemote ensures that no value is present for Remote, not even an explicit nil
func (o *RpmRpmRepository) UnsetRemote() {
	o.Remote.Unset()
}

// GetAutopublish returns the Autopublish field value if set, zero value otherwise.
func (o *RpmRpmRepository) GetAutopublish() bool {
	if o == nil || IsNil(o.Autopublish) {
		var ret bool
		return ret
	}
	return *o.Autopublish
}

// GetAutopublishOk returns a tuple with the Autopublish field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpmRpmRepository) GetAutopublishOk() (*bool, bool) {
	if o == nil || IsNil(o.Autopublish) {
		return nil, false
	}
	return o.Autopublish, true
}

// HasAutopublish returns a boolean if a field has been set.
func (o *RpmRpmRepository) HasAutopublish() bool {
	if o != nil && !IsNil(o.Autopublish) {
		return true
	}

	return false
}

// SetAutopublish gets a reference to the given bool and assigns it to the Autopublish field.
func (o *RpmRpmRepository) SetAutopublish(v bool) {
	o.Autopublish = &v
}

// GetMetadataSigningService returns the MetadataSigningService field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RpmRpmRepository) GetMetadataSigningService() string {
	if o == nil || IsNil(o.MetadataSigningService.Get()) {
		var ret string
		return ret
	}
	return *o.MetadataSigningService.Get()
}

// GetMetadataSigningServiceOk returns a tuple with the MetadataSigningService field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RpmRpmRepository) GetMetadataSigningServiceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MetadataSigningService.Get(), o.MetadataSigningService.IsSet()
}

// HasMetadataSigningService returns a boolean if a field has been set.
func (o *RpmRpmRepository) HasMetadataSigningService() bool {
	if o != nil && o.MetadataSigningService.IsSet() {
		return true
	}

	return false
}

// SetMetadataSigningService gets a reference to the given NullableString and assigns it to the MetadataSigningService field.
func (o *RpmRpmRepository) SetMetadataSigningService(v string) {
	o.MetadataSigningService.Set(&v)
}
// SetMetadataSigningServiceNil sets the value for MetadataSigningService to be an explicit nil
func (o *RpmRpmRepository) SetMetadataSigningServiceNil() {
	o.MetadataSigningService.Set(nil)
}

// UnsetMetadataSigningService ensures that no value is present for MetadataSigningService, not even an explicit nil
func (o *RpmRpmRepository) UnsetMetadataSigningService() {
	o.MetadataSigningService.Unset()
}

// GetPackageSigningService returns the PackageSigningService field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RpmRpmRepository) GetPackageSigningService() string {
	if o == nil || IsNil(o.PackageSigningService.Get()) {
		var ret string
		return ret
	}
	return *o.PackageSigningService.Get()
}

// GetPackageSigningServiceOk returns a tuple with the PackageSigningService field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RpmRpmRepository) GetPackageSigningServiceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PackageSigningService.Get(), o.PackageSigningService.IsSet()
}

// HasPackageSigningService returns a boolean if a field has been set.
func (o *RpmRpmRepository) HasPackageSigningService() bool {
	if o != nil && o.PackageSigningService.IsSet() {
		return true
	}

	return false
}

// SetPackageSigningService gets a reference to the given NullableString and assigns it to the PackageSigningService field.
func (o *RpmRpmRepository) SetPackageSigningService(v string) {
	o.PackageSigningService.Set(&v)
}
// SetPackageSigningServiceNil sets the value for PackageSigningService to be an explicit nil
func (o *RpmRpmRepository) SetPackageSigningServiceNil() {
	o.PackageSigningService.Set(nil)
}

// UnsetPackageSigningService ensures that no value is present for PackageSigningService, not even an explicit nil
func (o *RpmRpmRepository) UnsetPackageSigningService() {
	o.PackageSigningService.Unset()
}

// GetPackageSigningFingerprint returns the PackageSigningFingerprint field value if set, zero value otherwise.
func (o *RpmRpmRepository) GetPackageSigningFingerprint() string {
	if o == nil || IsNil(o.PackageSigningFingerprint) {
		var ret string
		return ret
	}
	return *o.PackageSigningFingerprint
}

// GetPackageSigningFingerprintOk returns a tuple with the PackageSigningFingerprint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpmRpmRepository) GetPackageSigningFingerprintOk() (*string, bool) {
	if o == nil || IsNil(o.PackageSigningFingerprint) {
		return nil, false
	}
	return o.PackageSigningFingerprint, true
}

// HasPackageSigningFingerprint returns a boolean if a field has been set.
func (o *RpmRpmRepository) HasPackageSigningFingerprint() bool {
	if o != nil && !IsNil(o.PackageSigningFingerprint) {
		return true
	}

	return false
}

// SetPackageSigningFingerprint gets a reference to the given string and assigns it to the PackageSigningFingerprint field.
func (o *RpmRpmRepository) SetPackageSigningFingerprint(v string) {
	o.PackageSigningFingerprint = &v
}

// GetRetainPackageVersions returns the RetainPackageVersions field value if set, zero value otherwise.
func (o *RpmRpmRepository) GetRetainPackageVersions() int64 {
	if o == nil || IsNil(o.RetainPackageVersions) {
		var ret int64
		return ret
	}
	return *o.RetainPackageVersions
}

// GetRetainPackageVersionsOk returns a tuple with the RetainPackageVersions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpmRpmRepository) GetRetainPackageVersionsOk() (*int64, bool) {
	if o == nil || IsNil(o.RetainPackageVersions) {
		return nil, false
	}
	return o.RetainPackageVersions, true
}

// HasRetainPackageVersions returns a boolean if a field has been set.
func (o *RpmRpmRepository) HasRetainPackageVersions() bool {
	if o != nil && !IsNil(o.RetainPackageVersions) {
		return true
	}

	return false
}

// SetRetainPackageVersions gets a reference to the given int64 and assigns it to the RetainPackageVersions field.
func (o *RpmRpmRepository) SetRetainPackageVersions(v int64) {
	o.RetainPackageVersions = &v
}

// GetChecksumType returns the ChecksumType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RpmRpmRepository) GetChecksumType() PackageChecksumTypeEnum {
	if o == nil || IsNil(o.ChecksumType.Get()) {
		var ret PackageChecksumTypeEnum
		return ret
	}
	return *o.ChecksumType.Get()
}

// GetChecksumTypeOk returns a tuple with the ChecksumType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RpmRpmRepository) GetChecksumTypeOk() (*PackageChecksumTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return o.ChecksumType.Get(), o.ChecksumType.IsSet()
}

// HasChecksumType returns a boolean if a field has been set.
func (o *RpmRpmRepository) HasChecksumType() bool {
	if o != nil && o.ChecksumType.IsSet() {
		return true
	}

	return false
}

// SetChecksumType gets a reference to the given NullablePackageChecksumTypeEnum and assigns it to the ChecksumType field.
func (o *RpmRpmRepository) SetChecksumType(v PackageChecksumTypeEnum) {
	o.ChecksumType.Set(&v)
}
// SetChecksumTypeNil sets the value for ChecksumType to be an explicit nil
func (o *RpmRpmRepository) SetChecksumTypeNil() {
	o.ChecksumType.Set(nil)
}

// UnsetChecksumType ensures that no value is present for ChecksumType, not even an explicit nil
func (o *RpmRpmRepository) UnsetChecksumType() {
	o.ChecksumType.Unset()
}

// GetRepoConfig returns the RepoConfig field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RpmRpmRepository) GetRepoConfig() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.RepoConfig
}

// GetRepoConfigOk returns a tuple with the RepoConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RpmRpmRepository) GetRepoConfigOk() (*interface{}, bool) {
	if o == nil || IsNil(o.RepoConfig) {
		return nil, false
	}
	return &o.RepoConfig, true
}

// HasRepoConfig returns a boolean if a field has been set.
func (o *RpmRpmRepository) HasRepoConfig() bool {
	if o != nil && !IsNil(o.RepoConfig) {
		return true
	}

	return false
}

// SetRepoConfig gets a reference to the given interface{} and assigns it to the RepoConfig field.
func (o *RpmRpmRepository) SetRepoConfig(v interface{}) {
	o.RepoConfig = v
}

// GetCompressionType returns the CompressionType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RpmRpmRepository) GetCompressionType() CompressionTypeEnum {
	if o == nil || IsNil(o.CompressionType.Get()) {
		var ret CompressionTypeEnum
		return ret
	}
	return *o.CompressionType.Get()
}

// GetCompressionTypeOk returns a tuple with the CompressionType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RpmRpmRepository) GetCompressionTypeOk() (*CompressionTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompressionType.Get(), o.CompressionType.IsSet()
}

// HasCompressionType returns a boolean if a field has been set.
func (o *RpmRpmRepository) HasCompressionType() bool {
	if o != nil && o.CompressionType.IsSet() {
		return true
	}

	return false
}

// SetCompressionType gets a reference to the given NullableCompressionTypeEnum and assigns it to the CompressionType field.
func (o *RpmRpmRepository) SetCompressionType(v CompressionTypeEnum) {
	o.CompressionType.Set(&v)
}
// SetCompressionTypeNil sets the value for CompressionType to be an explicit nil
func (o *RpmRpmRepository) SetCompressionTypeNil() {
	o.CompressionType.Set(nil)
}

// UnsetCompressionType ensures that no value is present for CompressionType, not even an explicit nil
func (o *RpmRpmRepository) UnsetCompressionType() {
	o.CompressionType.Unset()
}

// GetLayout returns the Layout field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RpmRpmRepository) GetLayout() LayoutEnum {
	if o == nil || IsNil(o.Layout.Get()) {
		var ret LayoutEnum
		return ret
	}
	return *o.Layout.Get()
}

// GetLayoutOk returns a tuple with the Layout field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RpmRpmRepository) GetLayoutOk() (*LayoutEnum, bool) {
	if o == nil {
		return nil, false
	}
	return o.Layout.Get(), o.Layout.IsSet()
}

// HasLayout returns a boolean if a field has been set.
func (o *RpmRpmRepository) HasLayout() bool {
	if o != nil && o.Layout.IsSet() {
		return true
	}

	return false
}

// SetLayout gets a reference to the given NullableLayoutEnum and assigns it to the Layout field.
func (o *RpmRpmRepository) SetLayout(v LayoutEnum) {
	o.Layout.Set(&v)
}
// SetLayoutNil sets the value for Layout to be an explicit nil
func (o *RpmRpmRepository) SetLayoutNil() {
	o.Layout.Set(nil)
}

// UnsetLayout ensures that no value is present for Layout, not even an explicit nil
func (o *RpmRpmRepository) UnsetLayout() {
	o.Layout.Unset()
}

func (o RpmRpmRepository) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RpmRpmRepository) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PulpLabels) {
		toSerialize["pulp_labels"] = o.PulpLabels
	}
	toSerialize["name"] = o.Name
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.RetainRepoVersions.IsSet() {
		toSerialize["retain_repo_versions"] = o.RetainRepoVersions.Get()
	}
	if o.Remote.IsSet() {
		toSerialize["remote"] = o.Remote.Get()
	}
	if !IsNil(o.Autopublish) {
		toSerialize["autopublish"] = o.Autopublish
	}
	if o.MetadataSigningService.IsSet() {
		toSerialize["metadata_signing_service"] = o.MetadataSigningService.Get()
	}
	if o.PackageSigningService.IsSet() {
		toSerialize["package_signing_service"] = o.PackageSigningService.Get()
	}
	if !IsNil(o.PackageSigningFingerprint) {
		toSerialize["package_signing_fingerprint"] = o.PackageSigningFingerprint
	}
	if !IsNil(o.RetainPackageVersions) {
		toSerialize["retain_package_versions"] = o.RetainPackageVersions
	}
	if o.ChecksumType.IsSet() {
		toSerialize["checksum_type"] = o.ChecksumType.Get()
	}
	if o.RepoConfig != nil {
		toSerialize["repo_config"] = o.RepoConfig
	}
	if o.CompressionType.IsSet() {
		toSerialize["compression_type"] = o.CompressionType.Get()
	}
	if o.Layout.IsSet() {
		toSerialize["layout"] = o.Layout.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RpmRpmRepository) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRpmRpmRepository := _RpmRpmRepository{}

	err = json.Unmarshal(data, &varRpmRpmRepository)

	if err != nil {
		return err
	}

	*o = RpmRpmRepository(varRpmRpmRepository)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "pulp_labels")
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "retain_repo_versions")
		delete(additionalProperties, "remote")
		delete(additionalProperties, "autopublish")
		delete(additionalProperties, "metadata_signing_service")
		delete(additionalProperties, "package_signing_service")
		delete(additionalProperties, "package_signing_fingerprint")
		delete(additionalProperties, "retain_package_versions")
		delete(additionalProperties, "checksum_type")
		delete(additionalProperties, "repo_config")
		delete(additionalProperties, "compression_type")
		delete(additionalProperties, "layout")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRpmRpmRepository struct {
	value *RpmRpmRepository
	isSet bool
}

func (v NullableRpmRpmRepository) Get() *RpmRpmRepository {
	return v.value
}

func (v *NullableRpmRpmRepository) Set(val *RpmRpmRepository) {
	v.value = val
	v.isSet = true
}

func (v NullableRpmRpmRepository) IsSet() bool {
	return v.isSet
}

func (v *NullableRpmRpmRepository) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRpmRpmRepository(val *RpmRpmRepository) *NullableRpmRpmRepository {
	return &NullableRpmRpmRepository{value: val, isSet: true}
}

func (v NullableRpmRpmRepository) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRpmRpmRepository) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


